/**
 * Generated by webmcp-codegen. This file is fully regenerated on every run.
 * Import registerAllTools() once at app startup:
 *
 *   import { registerAllTools } from "./webmcp";
 *   await registerAllTools();
 */

import { registerListPets } from "./list-pets.webmcp";
import { registerCreatePet } from "./create-pet.webmcp";
import { registerGetPet } from "./get-pet.webmcp";
import { registerDeletePet } from "./delete-pet.webmcp";
import { registerAdoptPet } from "./adopt-pet.webmcp";

const registrations = [
  registerListPets,
  registerCreatePet,
  registerGetPet,
  registerDeletePet,
  registerAdoptPet
];

/**
 * Register every generated tool with WebMCP. One tool failing (for example
 * because the page's Permissions-Policy disables tools) never takes the
 * others down with it. The failure is logged and registration continues.
 */
export async function registerAllTools(signal?: AbortSignal): Promise<void> {
  for (const register of registrations) {
    try {
      await register(signal);
    } catch (error) {
      console.warn("[webmcp-codegen] a tool failed to register:", error);
    }
  }
  // Drop journey definitions into ./journeys/ and re-run `generate`:
  // the next barrel registers every createJourney() export it finds there.
}
