import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import type { ReviewedTool } from "../types.js";
import { tools } from "./tools.js";

/** A small reviewed tool, as the safety layer would have produced it. */
function reviewedTool(overrides: Partial<ReviewedTool> = {}): ReviewedTool {
  return {
    id: "GET /orders/{id}",
    name: "get-order-status",
    source: { kind: "openapi", ref: "GET /orders/{id}" },
    inputSchema: {
      type: "object",
      properties: { orderId: { type: "string", description: "The order ID" } },
      required: ["orderId"],
    },
    inputTypeName: "GetOrderStatusInput",
    httpMethod: "GET",
    pathTemplate: "/orders/{orderId}",
    paramLocations: { path: ["orderId"], query: [], body: [] },
    sideEffect: "read",
    endpointRole: "endpoint",
    enabledByDefault: true,
    withheld: false,
    requiresAuth: false,
    description: "Returns the current status and tracking info for an order by ID.",
    descriptionSource: "openapi-summary",
    riskTier: "safe-read",
    hints: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      untrustedContentHint: false,
    },
    piiInOutput: [],
    ...overrides,
  };
}

/** Write a run's files to disk, so the next run sees them as "existing". */
async function writeAll(files: { path: string; contents: string }[]): Promise<void> {
  for (const file of files) {
    await mkdir(dirname(file.path), { recursive: true });
    await writeFile(file.path, file.contents);
  }
}

describe("js generator", () => {
  let cwd: string;

  beforeEach(async () => {
    cwd = await mkdtemp(join(tmpdir(), "webmcp-codegen-js-"));
  });

  afterEach(async () => {
    await rm(cwd, { recursive: true, force: true });
  });

  it("emits a live raw caller (fetchX) that the default execute composes", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.contents).toContain("export async function fetchGetOrderStatus(");
    expect(tool?.contents).toContain("const data = await fetchGetOrderStatus(input, signal);");
  });

  it("scaffolds the journey factory and never reports it as an orphan", async () => {
    // Simulate a previous run's factory sitting on disk.
    await mkdir(join(cwd, "src/webmcp"), { recursive: true });
    await writeFile(join(cwd, "src/webmcp/journey.webmcp.ts"), "// previously scaffolded\n");

    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const helper = files.find((file) => file.path.endsWith("webmcp/journey.webmcp.ts"));
    expect(helper).toBeDefined();
    expect(helper?.contents).toContain("export function createJourney(");

    // Generator-owned, so the orphan report must leave it alone.
    const barrel = files.find((file) => file.path.endsWith("webmcp/index.ts"));
    expect((barrel?.notes ?? []).join("\n")).not.toContain("journey.webmcp.ts");
  });

  it("registers journey files found in the journeys folder", async () => {
    await mkdir(join(cwd, "src/webmcp/journeys"), { recursive: true });
    await writeFile(
      join(cwd, "src/webmcp/journeys/document-trip.webmcp.ts"),
      "// the user's journey definition\n",
    );

    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const barrel = files.find((file) => file.path.endsWith("webmcp/index.ts"));
    expect(barrel?.contents).toContain(
      'import * as journeyModule0 from "./journeys/document-trip.webmcp";',
    );
    expect(barrel?.contents).toContain("await registerJourneys(journeyModules, signal);");
    const runtime = files.find((file) => file.path.endsWith("webmcp/runtime.webmcp.ts"));
    expect(runtime?.contents).toContain("export async function registerJourneys(");
  });

  it("scaffolds the WebMCP skill file at the cross-client skills location", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const skill = files.find((file) => file.path.endsWith(".agents/skills/webmcp-tools/SKILL.md"));
    expect(skill).toBeDefined();
    expect(skill?.action).toBe("create");
    expect(skill?.contents).toContain("name: webmcp-tools");
    expect(skill?.contents).toContain("Regenerated by webmcp-codegen");

    // A copy already on disk matching the asset reports unchanged.
    const skillPath = join(cwd, ".agents/skills/webmcp-tools/SKILL.md");
    await mkdir(dirname(skillPath), { recursive: true });
    await writeFile(skillPath, skill?.contents ?? "");
    const again = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const skillAgain = again.find((file) =>
      file.path.endsWith(".agents/skills/webmcp-tools/SKILL.md"),
    );
    expect(skillAgain?.action).toBe("unchanged");
  });

  it("caps tool results at the 1.5K output budget in the shared runtime", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const runtime = files.find((file) => file.path.endsWith("runtime.webmcp.ts"));
    expect(runtime?.contents).toContain("TOOL_OUTPUT_MAX");
    expect(runtime?.contents).toContain("truncated to fit the 1.5K output budget");
  });

  it("emits a runtime, a barrel, and one file per tool", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const paths = files.map((file) => file.path);
    expect(paths).toContain(join(cwd, "src/webmcp/runtime.webmcp.ts"));
    expect(paths).toContain(join(cwd, "src/webmcp/index.ts"));
    expect(paths).toContain(join(cwd, "src/webmcp/get-order-status.webmcp.ts"));
  });

  it("generated tool files carry the contract and the merge markers", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.action).toBe("create");
    expect(tool?.contents).toContain('name: "get-order-status"');
    expect(tool?.contents).toContain("Do not edit this region");
    expect(tool?.contents).toContain("Your code below survives regeneration");
    expect(tool?.contents).toContain("export type GetOrderStatusInput");
    expect(tool?.contents).toContain("executeGetOrderStatus");
    // The agent-facing schema must never contain an unresolved $ref.
    expect(tool?.contents).not.toContain("$ref");
  });

  it("keeps the developer's execute() across regenerations", async () => {
    const output = tools({ outDir: "src/webmcp" });
    const toolPath = join(cwd, "src/webmcp/get-order-status.webmcp.ts");

    // First run creates the file; then the developer edits execute().
    const first = await output.generate([reviewedTool()], cwd);
    await writeAll(first);
    const before = await readFile(toolPath, "utf8");
    const implemented = before.replace(
      "return toolResult(data);",
      'return { content: [{ type: "text", text: "Status: shipped" }] }; // my hand-written code',
    );
    await writeFile(toolPath, implemented);

    // Second run, with a changed description (the API contract evolved).
    const second = await output.generate(
      [reviewedTool({ description: "Get an order's live status." })],
      cwd,
    );
    const updated = second.find((file) => file.path === toolPath);
    expect(updated?.action).toBe("update");
    // The contract was regenerated...
    expect(updated?.contents).toContain("Get an order's live status.");
    // ...but the hand-written execute() survived, word for word.
    expect(updated?.contents).toContain("my hand-written code");
  });

  it("read tools are born with a working request, not a TODO", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    // The scaffold calls the real endpoint with the path param interpolated.
    // biome-ignore lint/suspicious/noTemplateCurlyInString: asserting on generated source, which contains a template literal
    expect(tool?.contents).toContain("await callApi(`/orders/${input.orderId}`");
    expect(tool?.contents).toContain('"GET"');
    expect(tool?.contents).not.toContain("Not implemented");
    expect(tool?.contents).not.toContain("toolDisabled(");
  });

  it("withheld tools do not register: the registration is a commented fence", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [
        reviewedTool({
          name: "cancel-order",
          inputTypeName: "CancelOrderInput",
          httpMethod: "POST",
          pathTemplate: "/orders/{orderId}/cancel",
          sideEffect: "destructive",
          enabledByDefault: false,
          withheld: true,
          riskTier: "destructive-confirm",
        }),
      ],
      cwd,
    );
    const tool = files.find((file) => file.path.includes("cancel-order"));
    // No live registration: the agent never sees the tool.
    // Line-anchored: the live call is gone; only the commented fence remains.
    expect(tool?.contents).not.toContain("\n  await modelContext.registerTool(");
    expect(tool?.contents).toContain("//   await modelContext.registerTool(");
    // Commented like an editor's toggle-comment: fixed marker column, original
    // indentation preserved, so uncommenting restores working code.
    expect(tool?.contents).toContain("//       ...cancelOrderTool,");
    // The import reflects it: getModelContext is part of the fence, not the
    // file - but callApi stays live, because the raw caller (fetchX) the
    // generated region emits is live too: journeys compose withheld tools.
    expect(tool?.contents).toContain('import { callApi, toolDisabled } from "./runtime.webmcp";');
    expect(tool?.contents).toContain("export async function fetchCancelOrder(");
    // The execute scaffold still refuses politely if someone registers it by hand.
    expect(tool?.contents).toContain('return toolDisabled("cancel-order.webmcp.ts");');
    // And the header says what "withheld" means.
    expect(tool?.contents).toContain("Starts withheld: not registered until you enable it");
  });

  it("enabled endpoint tools carry the co-browsing extension point", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.contents).toContain("Make the effect visible");
  });

  it("emits the spec's annotations into the tool definition", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [
        reviewedTool({
          hints: {
            readOnlyHint: true,
            destructiveHint: false,
            idempotentHint: true,
            untrustedContentHint: true,
          },
        }),
      ],
      cwd,
    );
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.contents).toContain("annotations: {");
    expect(tool?.contents).toContain("readOnlyHint: true");
    expect(tool?.contents).toContain("untrustedContentHint: true");
  });

  it("emits a human-facing title and marks destructive tools consequential", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [
        reviewedTool(),
        reviewedTool({
          name: "delete-order",
          httpMethod: "DELETE",
          riskTier: "destructive-confirm",
          sideEffect: "write",
          enabledByDefault: false,
          withheld: true,
        }),
      ],
      cwd,
    );
    const read = files.find((file) => file.path.includes("get-order-status"));
    const destructive = files.find((file) => file.path.includes("delete-order"));
    expect(read?.contents).toContain('title: "Get Order Status"');
    expect(read?.contents).toContain("consequentialHint: false");
    expect(destructive?.contents).toContain('title: "Delete Order"');
    expect(destructive?.contents).toContain("consequentialHint: true");
  });

  it("passes configured exposedTo origins to registerTool", async () => {
    const files = await tools({
      outDir: "src/webmcp",
      exposedTo: ["https://partner.example"],
    }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.contents).toContain('{ signal, exposedTo: ["https://partner.example"] }');
  });

  it("registration skips quietly when the browser has no WebMCP", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.contents).toContain("if (!modelContext) return;");
    const runtime = files.find((file) => file.path.includes("runtime.webmcp"));
    // A missing runtime is a normal page load: null and one quiet log line,
    // never a throw per tool.
    expect(runtime?.contents).toContain("getModelContext(): ModelContext | null");
    expect(runtime?.contents).toContain("console.info(");
    expect(runtime?.contents).not.toContain('WebMCP is not available in this browser. " +');
  });

  it("execute failures become readable error results, never throws", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    // The generated wrapper converts any throw into an error the agent can
    // read; a rejected execute would arrive as a message-less UnknownError.
    expect(tool?.contents).toContain("return asToolError(error);");
    const runtime = files.find((file) => file.path.includes("runtime.webmcp"));
    expect(runtime?.contents).toContain('error.name === "AbortError"');
  });

  it("threads the execute context's signal through to fetch", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate([reviewedTool()], cwd);
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.contents).toContain(
      "executeGetOrderStatus(input as GetOrderStatusInput, context?.signal)",
    );
    expect(tool?.contents).toContain("signal?: AbortSignal");
    const runtime = files.find((file) => file.path.includes("runtime.webmcp"));
    expect(runtime?.contents).toContain("signal: options.signal");
  });

  it("mutations start disabled, with working code one uncomment away", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [
        reviewedTool({
          name: "cancel-order",
          inputTypeName: "CancelOrderInput",
          httpMethod: "POST",
          pathTemplate: "/orders/{orderId}/cancel",
          sideEffect: "destructive",
          endpointRole: "endpoint",
          enabledByDefault: false,
          withheld: false,
          riskTier: "destructive-confirm",
          hints: {
            readOnlyHint: false,
            destructiveHint: true,
            idempotentHint: false,
            untrustedContentHint: false,
          },
        }),
      ],
      cwd,
    );
    const tool = files.find((file) => file.path.includes("cancel-order"));
    // Disabled notice first, the working call right below it, commented out
    // - and it composes the generated region's raw caller like every other
    // endpoint-backed tool.
    expect(tool?.contents).toContain('return toolDisabled("cancel-order.webmcp.ts");');
    expect(tool?.contents).toContain("// const data = await fetchCancelOrder(input, signal);");
    // The consent gate is generated, not left as a comment for humans to remember.
    expect(tool?.contents).toContain("requestUserConfirmation(");
    expect(tool?.contents).toContain("The user declined this action.");
  });

  it("imports only the runtime helpers the file actually uses", async () => {
    // Strict lint configs (Next.js builds fail on no-unused-vars errors)
    // reject a generated file that imports helpers only its comments mention.
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [
        reviewedTool(), // enabled read with a route
        reviewedTool({
          name: "cancel-order",
          inputTypeName: "CancelOrderInput",
          httpMethod: "POST",
          pathTemplate: "/orders/{orderId}/cancel",
          sideEffect: "destructive",
          enabledByDefault: false,
          withheld: false,
          riskTier: "destructive-confirm",
        }),
        reviewedTool({
          name: "create-trip",
          inputTypeName: "CreateTripInput",
          source: { kind: "schema", ref: "CreateTripInput" },
          httpMethod: undefined,
          pathTemplate: undefined,
          paramLocations: undefined,
          sideEffect: "write",
          riskTier: "write-confirm",
        }),
      ],
      cwd,
    );
    const enabledRead = files.find((file) => file.path.includes("get-order-status"));
    expect(enabledRead?.contents).toContain(
      'import { getModelContext, callApi, toolResult, asToolError } from "./runtime.webmcp";',
    );

    // The disabled tool's request is commented out, but its generated raw
    // caller (fetchX) is live - so callApi is in the import line, and the
    // enable instructions only name what's genuinely missing.
    const disabledWrite = files.find((file) => file.path.includes("cancel-order"));
    expect(disabledWrite?.contents).toContain(
      'import { getModelContext, requestUserConfirmation, callApi, asToolError, toolDisabled } from "./runtime.webmcp";',
    );
    expect(disabledWrite?.contents).toContain("add toolResult to the import above");

    // A standalone schema tool has no route to call: no callApi. It is a
    // write, so the confirmation gate's helper is imported and used.
    const standalone = files.find((file) => file.path.includes("create-trip"));
    expect(standalone?.contents).toContain(
      'import { getModelContext, requestUserConfirmation, toolResult, asToolError } from "./runtime.webmcp";',
    );
  });

  it("respects an absolute outDir instead of nesting it under the project", async () => {
    // path.join(cwd, "/abs/out") silently becomes cwd/abs/out; resolve does
    // the right thing. An absolute --out must write exactly where it points.
    const absoluteOut = await mkdtemp(join(tmpdir(), "webmcp-codegen-out-"));
    try {
      const files = await tools({ outDir: absoluteOut }).generate([reviewedTool()], cwd);
      expect(files.length).toBeGreaterThan(0);
      for (const file of files) {
        // The skill file is the one exception: it lives at the project root's
        // cross-client skills location, not under outDir.
        if (file.path.endsWith(".agents/skills/webmcp-tools/SKILL.md")) continue;
        expect(file.path.startsWith(absoluteOut)).toBe(true);
        expect(file.path.startsWith(cwd)).toBe(false);
      }
    } finally {
      await rm(absoluteOut, { recursive: true, force: true });
    }
  });

  it("builds query strings and JSON bodies from the param locations", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [
        reviewedTool({
          name: "search-assets",
          inputTypeName: "SearchAssetsInput",
          httpMethod: "POST",
          pathTemplate: "/search",
          paramLocations: { path: [], query: ["limit"], body: ["query", "tags"] },
        }),
      ],
      cwd,
    );
    const tool = files.find((file) => file.path.includes("search-assets"));
    expect(tool?.contents).toContain(
      'callApi("/search", { method: "POST", query: { limit: input.limit }, body: { query: input.query, tags: input.tags }, signal })',
    );
  });

  it("keeps a non-local server URL, but a local one falls back to same-origin", async () => {
    // A spec's servers[0] is often a dev URL. Baking localhost into the
    // generated fetch makes every deployed tool call the visitor's own
    // machine, so a local base must fall back to a relative (same-origin)
    // path. A real public API host is kept as-is.
    const local = await tools({ outDir: "src/webmcp" }).generate(
      [reviewedTool({ serverUrl: "http://localhost:3001" })],
      cwd,
    );
    const localTool = local.find((file) => file.path.includes("get-order-status"));
    // biome-ignore lint/suspicious/noTemplateCurlyInString: asserting on generated source
    expect(localTool?.contents).toContain("await callApi(`/orders/${input.orderId}`");
    expect(localTool?.contents).not.toContain("localhost");

    const publicApi = await tools({ outDir: "src/webmcp" }).generate(
      [reviewedTool({ serverUrl: "https://api.example.com" })],
      cwd,
    );
    const publicTool = publicApi.find((file) => file.path.includes("get-order-status"));
    expect(publicTool?.contents).toContain(
      // biome-ignore lint/suspicious/noTemplateCurlyInString: asserting on generated source
      "await callApi(`https://api.example.com${`/orders/${input.orderId}`}`",
    );
  });

  it("falls back to an honest TODO when the source knows no route", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [reviewedTool({ httpMethod: undefined, pathTemplate: undefined, paramLocations: undefined })],
      cwd,
    );
    const tool = files.find((file) => file.path.includes("get-order-status"));
    expect(tool?.contents).toContain("TODO: call your app's existing code here");
  });

  it("never clobbers a file whose markers were removed; it reports a conflict", async () => {
    const output = tools({ outDir: "src/webmcp" });
    const toolPath = join(cwd, "src/webmcp/get-order-status.webmcp.ts");
    await mkdir(join(cwd, "src/webmcp"), { recursive: true });
    await writeFile(toolPath, "// my totally hand-written file, no markers\n");

    const files = await output.generate([reviewedTool()], cwd);
    const conflicted = files.find((file) => file.path === toolPath);
    expect(conflicted?.conflict).toBe(`${toolPath}.new`);
    // The existing file's contents are reported back untouched.
    expect(conflicted?.contents).toContain("my totally hand-written file");
  });

  it("scaffolds a PII notice for tools whose responses carry PII", async () => {
    const files = await tools({ outDir: "src/webmcp" }).generate(
      [
        reviewedTool({
          name: "get-me",
          inputTypeName: "GetMeInput",
          pathTemplate: "/me",
          paramLocations: { path: [], query: [], body: [] },
          piiInOutput: ["user.email"],
        }),
      ],
      cwd,
    );
    const tool = files.find((file) => file.path.includes("get-me"));
    expect(tool?.contents).toContain("user.email");
  });

  it("reports unchanged when nothing about the contract moved", async () => {
    const output = tools({ outDir: "src/webmcp" });
    await writeAll(await output.generate([reviewedTool()], cwd));

    const second = await output.generate([reviewedTool()], cwd);
    const toolFile = second.find((file) => file.path.includes("get-order-status"));
    expect(toolFile?.action).toBe("unchanged");
  });

  it("a rename between runs carries the owned execute() to the new filename", async () => {
    const output = tools({ outDir: "src/webmcp" });
    await writeAll(await output.generate([reviewedTool()], cwd));

    // The developer edits their region.
    const oldPath = join(cwd, "src/webmcp/get-order-status.webmcp.ts");
    const before = await readFile(oldPath, "utf8");
    await writeFile(
      oldPath,
      before.replace(
        "export async function execute",
        "// MY CUSTOM CODE\nexport async function execute",
      ),
    );

    // Next run: the same endpoint now resolves to a different name.
    const renamed = reviewedTool({ name: "get-order" });
    const files = await output.generate([renamed], cwd);

    const moved = files.find((file) => file.path.endsWith("get-order.webmcp.ts"));
    expect(moved?.contents).toContain("MY CUSTOM CODE");
    expect(moved?.notes?.some((note) => note.includes("Followed the rename"))).toBe(true);
  });

  it("a tool never inherits a stranger's execute() left at its filename", async () => {
    const output = tools({ outDir: "src/webmcp" });

    // Two endpoints whose files are on disk under their old names.
    await writeAll(
      await output.generate(
        [
          reviewedTool(), // get-order-status -> GET /orders/{id}
          reviewedTool({
            id: "DELETE /admin/orders/{id}",
            name: "delete-order",
            source: { kind: "openapi", ref: "DELETE /admin/orders/{id}" },
            httpMethod: "DELETE",
            sideEffect: "destructive",
            enabledByDefault: false,
            withheld: true,
            riskTier: "destructive-confirm",
          }),
        ],
        cwd,
      ),
    );

    // The spec changes: the read endpoint is deleted, and a NEW endpoint
    // appears whose derived name lands on the old file's exact filename.
    // The old file must move aside, not have its body inherited.
    const usurper = reviewedTool({
      id: "GET /shipping/orders/{id}",
      name: "delete-order",
      source: { kind: "openapi", ref: "GET /shipping/orders/{id}" },
    });
    const files = await output.generate([usurper], cwd);

    const fresh = files.find((file) => file.path.endsWith("delete-order.webmcp.ts"));
    // A fresh scaffold for the new endpoint, not the admin tool's body.
    expect(fresh?.contents).toContain("GET /shipping/orders/{id}");
    expect(fresh?.contents).not.toContain("DELETE /admin/orders/{id}");

    // The stranger was set aside, not destroyed.
    const aside = files.find((file) => file.path.endsWith("delete-order.webmcp.ts.orphaned"));
    expect(aside?.contents).toContain("DELETE /admin/orders/{id}");

    // And the endpoint that vanished entirely is reported as an orphan.
    const barrel = files.find((file) => file.path.endsWith("index.ts"));
    expect(barrel?.notes?.some((note) => note.includes("get-order-status.webmcp.ts"))).toBe(true);
  });
});
